Set WshShell = WScript.CreateObject("WScript.Shell")

' WshShell.Run "C:\projetos\podcast-cuts-creator\sourceContent\templates\photoshop\thumbnail-template.psd", 3
WshShell.Run "C:\DevProjects\podcast-cuts-creator\sourceContent\templates\photoshop\thumbnail-template.psd", 3

WScript.Sleep 3000

WshShell.AppActivate "Adobe Photoshop 2022"

' WScript.Sleep 5000
WScript.Sleep 20000

' WScript.Sleep 500
WScript.Sleep 5000
WshShell.SendKeys "%"
WScript.Sleep 500
WshShell.SendKeys "a"
WScript.Sleep 500
WshShell.SendKeys "p"
WScript.Sleep 500
WshShell.SendKeys "p"
WScript.Sleep 500
WshShell.SendKeys "{ENTER}"
WScript.Sleep 100
WshShell.SendKeys "{DOWN}"
WshShell.SendKeys "{DOWN}"
WshShell.SendKeys "{DOWN}"
WshShell.SendKeys "{DOWN}"
WshShell.SendKeys "{DOWN}"
WshShell.SendKeys "{DOWN}"
WshShell.SendKeys "{DOWN}"
WshShell.SendKeys "{DOWN}"
WshShell.SendKeys "{ENTER}"
WScript.Sleep 1000
WshShell.SendKeys "+{C}"
WshShell.SendKeys "+{;}"
WshShell.SendKeys "{\}"
WshShell.SendKeys "+{d}"
WshShell.SendKeys "{e}"
WshShell.SendKeys "{v}"
WshShell.SendKeys "+{p}"
WshShell.SendKeys "{r}"
WshShell.SendKeys "{o}"
WshShell.SendKeys "{j}"
WshShell.SendKeys "{e}"
WshShell.SendKeys "{c}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{s}"
' WshShell.SendKeys "{p}"
' WshShell.SendKeys "{r}"
' WshShell.SendKeys "{o}"
' WshShell.SendKeys "{j}"
' WshShell.SendKeys "{e}"
' WshShell.SendKeys "{t}"
' WshShell.SendKeys "{o}"
' WshShell.SendKeys "{s}"
WshShell.SendKeys "{\}"
WshShell.SendKeys "{p}"
WshShell.SendKeys "{o}"
WshShell.SendKeys "{d}"
WshShell.SendKeys "{c}"
WshShell.SendKeys "{a}"
WshShell.SendKeys "{s}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{-}"
WshShell.SendKeys "{c}"
WshShell.SendKeys "{u}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{s}"
WshShell.SendKeys "{-}"
WshShell.SendKeys "{c}"
WshShell.SendKeys "{r}"
WshShell.SendKeys "{e}"
WshShell.SendKeys "{a}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{o}"
WshShell.SendKeys "{r}"
WshShell.SendKeys "{\}"
WshShell.SendKeys "{s}"
WshShell.SendKeys "{o}"
WshShell.SendKeys "{u}"
WshShell.SendKeys "{r}"
WshShell.SendKeys "{c}"
WshShell.SendKeys "{e}"
WshShell.SendKeys "+{c}"
WshShell.SendKeys "{o}"
WshShell.SendKeys "{n}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{e}"
WshShell.SendKeys "{n}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{\}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{e}"
WshShell.SendKeys "{m}"
WshShell.SendKeys "{p}"
WshShell.SendKeys "{l}"
WshShell.SendKeys "{a}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{e}"
WshShell.SendKeys "{s}"
WshShell.SendKeys "{\}"
WshShell.SendKeys "{p}"
WshShell.SendKeys "{h}"
WshShell.SendKeys "{o}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{o}"
WshShell.SendKeys "{s}"
WshShell.SendKeys "{h}"
WshShell.SendKeys "{o}"
WshShell.SendKeys "{p}"
WshShell.SendKeys "{\}"
WshShell.SendKeys "{s}"
WshShell.SendKeys "{c}"
WshShell.SendKeys "{r}"
WshShell.SendKeys "{i}"
WshShell.SendKeys "{p}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "{s}"
WshShell.SendKeys "{\}"
WshShell.SendKeys "{s}"
WshShell.SendKeys "{c}"
WshShell.SendKeys "{r}"
WshShell.SendKeys "{i}"
WshShell.SendKeys "{p}"
WshShell.SendKeys "{t}"
WshShell.SendKeys "+{t}"
WshShell.SendKeys "{h}"
WshShell.SendKeys "{u}"
WshShell.SendKeys "{m}"
WshShell.SendKeys "{b}"
WshShell.SendKeys "{.}"
WshShell.SendKeys "{j}"
WshShell.SendKeys "{s}"
WScript.Sleep 100
WshShell.SendKeys "{ENTER}"